server:
  port: 9191
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: otus1.p12
    key-store-password: 111111
    key-alias: otus
    trust-store-type: PKCS12
    trust-store: truststore.p12
    trust-store-password: 111111